services:
  - type: web
    name: mood-backend
    env: python
    plan: free
    region: oregon

    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
